"""
Configuration settings for the onion simulator.
"""

# 2D Simulator Default Settings
DEFAULT_2D_ONION_DIAMETER = 5.0
DEFAULT_2D_ONION_LAYERS = 9
DEFAULT_2D_START_Y = 0.5
DEFAULT_2D_END_Y = 0.8
DEFAULT_2D_P1 = (0.2, 1.2)
DEFAULT_2D_P2 = (0.8, 1.0)

# 3D Simulator Default Settings
DEFAULT_3D_ONION_DIAMETER = 5.0
DEFAULT_3D_ONION_LAYERS = 9
DEFAULT_3D_START_Y = 0.5
DEFAULT_3D_END_Y = 0.8
DEFAULT_3D_P1 = (0.2, 1.2)
DEFAULT_3D_P2 = (0.8, 1.0)
DEFAULT_3D_VERTICAL_STRETCH = 1.2
DEFAULT_3D_TOP_FLATNESS = 0.3
DEFAULT_3D_BOTTOM_POINTINESS = 0.7
DEFAULT_3D_HORIZONTAL_RATIO = 0.9
DEFAULT_3D_PROFILE = 'onion1'  # Default SVG profile name

# Cutting Method Default Parameters
DEFAULT_CLASSIC_VERTICAL_CUTS = 10
DEFAULT_CLASSIC_HORIZONTAL_CUTS = 2

DEFAULT_KENJI_CUTS = 10
DEFAULT_KENJI_PCT_BELOW = 0.6

DEFAULT_JOSH_HORIZONTAL_CUTS = 3
DEFAULT_JOSH_VERTICAL_CUTS = 10
DEFAULT_JOSH_HORIZONTAL_DEPTH = 0.85
DEFAULT_JOSH_VERTICAL_HEIGHT = 0.17

# Visualization Settings
PLOTLY_HEIGHT_2D = 250
PLOTLY_WIDTH_2D = 500
PLOTLY_HEIGHT_3D = 400
PLOTLY_WIDTH_3D = 600

# URL Parameter Keys
URL_SETTINGS_KEY = 'settings' 